# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-xcmiscproto
Summary:    X.Org X11 Protocol xcmiscproto
Version:    1.2.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/xcmiscproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-xcmiscproto.yaml
Provides:   xcmiscproto


%description
This extension defines a protocol that provides Xlib two ways to 
query the server for available resource IDs.




%prep
%setup -q -n xcmiscproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/xcmiscproto.pc
%{_includedir}/X11/extensions/xcmiscstr.h
%{_includedir}/X11/extensions/xcmiscproto.h
%doc %{_docdir}/xcmiscproto/xc-misc.xml
# << files


